openapi: '3.0.2'
info:
  description: "Post administrator Twitter2"
  version: "1.0.0"
  title: "Twitter2"
servers:
  - url: localhost:3000
paths:
  /users:
    post:
      summary: "Agregar usuario"
      description: "Agregar un nuevo usuario"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/post_post"
      responses:
        200:
          description: Usuario creado exitosamente!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/newUser"
  /post:
    post:
      summary: "Agregar post"
      description: "Agregar un nuevo post"
      parameters:
        - in: header
          name: X-Email
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/post_post"
      responses:
        200:
          description: Usuario autenticado exitosamente!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/post_response"
        401:
          description: Error de autenticacion
  /posts:  
    get:
      summary: "Agregar post"
      description: "Agregar un nuevo post"
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: pageSize
          schema:
            type: integer
            default: 5
        - in: query
          name: authorEmail
          schema:
            type: string
      responses:
        200:
          description: Mostart todos los post
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/show_post"
        401:
          description: Error de autenticacion
  /post/{postId}/comment:
    post:
      summary: "Agregar comentario"
      description: "Agregar comentario a un post"
      parameters:
        - in: header
          name: X-Email
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/comment_post"
      responses:
        200:
          description: Usuario autenticado exitosamente!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/comment_response"
        401:
          description: Error de autenticacion
components:
  schemas:
    newUser:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
    post_post:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
    comment_post:
      type: object
      properties:
        content:
          type: string
    post_response:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
        createdAt:
          type: string
          format: date
        author:
          type: object
          properties:
            email:
              type: string
            name:
              type: string
    comment_response:
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        createdAt:
          type: string
          format: date
        author:
          type: object
          properties:
            email:
              type: string
            name:
              type: string
    show_post:
      type: object
      properties:
        page:
          type: integer
        pageSize:
          type: integer
        totalPages:
          type: integer
        posts:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              title:
                type: string
              content:
                type: string
              createdAt:
                type: string
                format: date
              author:
                type: object
                properties:
                  email:
                    type: string
                  name:
                    type: string
        comments:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              content:
                type: string
              createdAt:
                type: string
                format: date
              author:
                type: object
                properties:
                  email:
                    type: string
                  name:
                    type: string